
version: '3.7'

services:

  app:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    expose:
        - "19000"
        - "19001"
        - "19002"
    ports:
        - "19000:19000"
        - "19001:19001"
        - "19002:19002"
    volumes:
        - ./:/usr/src/app
    command: yarn start
    tty: true
    stdin_open: true
    environment:
        - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 
