ENV=.env

echo "SENTRY_PUBLIC_DNS=\"${SENTRY_PUBLIC_DNS}\"" > ${ENV}
echo "SENTRY_ORG=\"${SENTRY_ORG}\"" >> ${ENV}
echo "SENTRY_PROJECT=\"${SENTRY_PROJECT}\"" >> ${ENV}
echo "SENTRY_AUTH_TOKEN=\"${SENTRY_AUTH_TOKEN}\"" >> ${ENV}
echo "AGILECOM_API_KEY=\"${AGILECOM_API_KEY}\"" >> ${ENV}
echo "AGILECOM_API_BASE_URL=\"${AGILECOM_API_BASE_URL}\"" >> ${ENV}
echo "AGILECOM_API_USE_HTTP=\"${AGILECOM_API_USE_HTTP}\"" >> ${ENV}
