name: publish-staging

on:
  push:
    branches:
      - "staging"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint
      - run: yarn test

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: npx expo login --non-interactive -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}
        env:
          EXPO_USERNAME: ${{secrets.EXPO_USERNAME}}
          EXPO_PASSWORD: ${{secrets.EXPO_PASSWORD}}
      - run: yarn gen:dotenv
        env:
          SENTRY_PUBLIC_DNS: ${{secrets.SENTRY_PUBLIC_DNS}}
          SENTRY_ORG: ${{secrets.SENTRY_ORG}}
          SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          AGILECOM_API_KEY: ${{secrets.AGILECOM_API_KEY}}
          AGILECOM_API_BASE_URL: ${{secrets.AGILECOM_API_BASE_URL}}
          AGILECOM_API_USE_HTTP: ${{secrets.AGILECOM_API_USE_HTTP}}
      - run: yarn gen:manifest
      - run: npx expo publish --release-channel default --non-interactive
